version: '3'

services:
  webserver1:
    hostname: "ops-httpd1"
    image: "ops-httpd:2.4.1"
    build: ./Dockerfiles
    ports:
      - "8080:80"
  webserver2:
    hostname: "ops-httpd2"
    image: "ops-httpd:2.4.1"
    build: ./Dockerfiles
    ports:
      - "8081:80"
  nginx:
    image: "ops-nginx:1.21.4"
    build: .
    ports:
      - "80:80"
    depends_on:
      - webserver1
      - webserver2
